export enum MenuSections {
  COCKTAILS = "COCKTAILS",
  COCKTAILS_NO_ALCOHOL = "COCKTAILS_NO_ALCOHOL",
  DESSERTS_AND_COFFEE = "DESSERTS_AND_COFFEE",
  DRINKS = "DRINKS",
  FOOD = "FOOD",
  LIQUORS = "LIQUORS",
  MEZCALES = "MEZCALES",
  MIXOLOGY = "MIXOLOGY",
}