export enum Agaves {
  ARROQUEÑO = "ARROQUEÑO",
  CUIXE = "CUIXE",  
  ESPADIN = "ESPADIN",
  GUSANO = "GUSANO",
  JABALI = "JABALI",
  MEXICANO = "MEXICANO",
  OTHER = "OTHER",
  PECHUGA = "PECHUGA",
  TEPEZTATE = "TEPEZTATE",
  TOBALA = "TOBALA",
  CUPREATA = "CUPREATA",
}